# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5aadd50c5021abc21e715894572205f7bd8b8eb12131c214c6d85ee2131953fb378285b2539ca5379d88d7768fc6cc9747d78ece87254078883a94e2ddf4998b

test:
  secret_key_base: 7d4b3c6fc14a0f1337c1bebfd8227b9126e67ecc52c5f8983586ae6693ec0af3b82a9306c0cc1cb60812d3ad8d978c019d59ad625a9085b9b342f392a718b021

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
